kind: pipeline
type: docker
name: default

steps:

  - name: yarn
    image: node:latest
    commands:
      - yarn install --pure-lockfile --production
      - ./prepare_assets.sh

  - name: build
    image: golang
    commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s -extldflags "-static"' -o wireguard_ui_linux_amd64

  - name: upload
    image: plugins/s3
    settings:
      bucket: app-build-packages
      source: wireguard_ui_linux_amd64
      target: /wireguard_ui/app
