kind: pipeline
type: docker
name: default

workspace:
  path: /output

steps:
  - name: publish
    image: plugins/ecr
    settings:
      repo: wireguard-ui
      registry: 072805691757.dkr.ecr.us-east-1.amazonaws.com
      tags:
        - master
    when:
      branch:
        - master
